import type { Metadata } from "next";
import { kumbhSans, inter } from './fonts'
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html className={`${kumbhSans.variable} ${inter.variable}`} lang="en">

      <body className={kumbhSans.className}>
        <div className="bg-background-padding">
          {children}
        </div>
      </body>
    </html>
  );
}
